# Generated by Django 4.0.3 on 2022-04-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=6)),
                ('SponNo', models.CharField(max_length=100)),
                ('PhoneNo', models.CharField(max_length=15)),
                ('State', models.CharField(max_length=50)),
                ('LocalGov', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=15)),
            ],
        ),
    ]
