# Generated by Django 4.0.3 on 2022-05-03 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spon', '0002_members_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='Serial',
        ),
    ]
